version: '3'
services:

  video-resizer:
    container_name: video-resizer
    image: bellsoft/liberica-openjdk-debian:17
    restart: always
    ports:
      - "8080:8080"
    environment:
        TZ: "Asia/Seoul"
    volumes:
      - ./lib:/srv/video-resizer/lib
      - ./conf:/srv/video-resizer/conf
      - ./video:/srv/video-resizer/video
    command: bash -c "apt-get install -y ffmpeg; java -Djava.net.preferIPv4Stack=true -Dfile.encoding=utf-8 -jar /srv/video-resizer/lib/resizer-0.0.1-SNAPSHOT.jar --spring.config.location=file:/srv/video-resizer/conf/application-jh.yml"
